# fly.toml app configuration file generated for slimes on 2023-06-17T23:14:08-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "slimes"
primary_region = "scl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
